#include "DataFormats/Portable/interface/PortableHostCollectionReadRules.h"
#include "DataFormats/NGTSoATest/interface/PortableCollectionSoATest.h"
#include "DataFormats/NGTSoATest/interface/SoALayoutTest.h"

SET_PORTABLEHOSTCOLLECTION_READ_RULES(PhysicsObjCollection);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(PhysicsObjExtraCollection);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(CombinedPhysicsObjectCollection);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(PortableHostCollection<NGTSoA>);