#include "DataFormats/Portable/interface/PortableHostCollectionReadRules.h"
#include "DataFormats/Portable/interface/PortableHostObjectReadRules.h"
#include "RecoSoA/SoAProducers/interface/PortableCollectionSoATest.h"

SET_PORTABLEHOSTCOLLECTION_READ_RULES(SoAHostPositionCollection);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(SoAHostVelocityCollection);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(SoAHostYCoordinateCollection);
